export const types = Object.freeze({
    TODO_START_FETCHING: 'TODO_START_FETCHING',
    TODO_STOP_FETCHING: 'TODO_STOP_FETCHING',
    TODO_ERROR_FETCHING:'TODO_ERROR_FETCHING',
    TODO_FILL: 'TODO_FILL',
    TODO_TASK_FILL: 'TODO_TASK_FILL',
    TODO_TASK_RESET: 'TODO_TASK_RESET',
    TODO_TASK_ADD: 'TODO_TASK_ADD',
    TODO_TASK_UPDATE: 'TODO_TASK_UPDATE',
    TODO_TASK_DELETE: 'TODO_TASK_DELETE',
});